### ISSUE TITLE
Support for Influx 0.9.x

### ISSUE THREAD

**Issue by bscott** [google/cadvisor#943] opened 2015-10-28 02:03 UTC
When will support be added for InfluxDB 0.9.x?

**Comment by svenmueller** [comment] 2015-10-31 14:03
+1

**Comment by jmartine** [comment] 2015-11-02 16:58
+1

**Comment by chrisferry** [comment] 2015-11-02 21:38
Dupe of this: #743

**Comment by harunyardimci** [comment] 2015-11-02 22:27
+1

**Comment by berglh** [comment] 2015-11-02 23:11
+0.9

**Comment by bmlynarczyk** [comment] 2015-11-19 15:32
+1

**Comment by mboussaa** [comment] 2015-11-21 19:16
any updates on that integration?

**Comment by mmaquevice** [comment] 2015-11-28 17:51
+1

**Comment by chr0n1x** [comment] 2015-12-01 04:21
:+1:

**Comment by andrejvanderzee** [comment] 2015-12-03 06:24
+1

**Comment by jimmidyson** [comment] 2015-12-03 10:43
Closing as dupe of #743

**Closed by jimmidyson** 2015-12-03 10:43 UTC

**Comment by tkak** [comment] 2016-01-25 08:39
+1
