### ISSUE TITLE
What is the recommended way to find out cpu utilization of container

### ISSUE THREAD

**Issue by apratina** [google/cadvisor#2036] opened 2018-09-07 01:18 UTC
We have our container report `container_cpu_usage_seconds_total` metric in prometheus and we are using following query to fetch % cpu utilization for container :

```
sum by(container_instance_id)(rate(container_cpu_usage_seconds_total{}[5m])*100)
```

Is there any metric other than `container_cpu_usage_seconds_total` that can be used to calculate % cpu utilization of container?

**Comment by apratina** [comment] 2018-09-07 02:15
Sorry if I was not clear earlier. I am looking for % of cpu utilized by the container at any point of time. So it looks like there is no metric other than `container_cpu_usage_seconds_total ` to calculate it?

**Comment by dashpole** [comment] 2018-09-19 17:05
I think this is a duplicate of https://github.com/google/cadvisor/issues/2026.  Feel free to reopen if you that does not answer your question

**Closed by dashpole** 2018-09-19 17:05 UTC
Labels: kind/support
