### ISSUE TITLE
No disk capacity/usage is reported for Docker using the thinpool lvm devicemapper storage driver

### ISSUE THREAD

**Issue by csrwng** [google/cadvisor#920] opened 2015-10-15 19:49 UTC
Based on comments I see in the code, this is not implemented yet:
https://github.com/google/cadvisor/blob/master/fs/fs.go#L108
https://github.com/google/cadvisor/blob/master/fs/fs.go#L116

However, it's really important for Kubernetes image garbage collection to work on systems that typically use the thinpool lvm storage driver like RHEL or Fedora.

**Comment by csrwng** [comment] 2015-10-15 19:50
@jimmidyson @derekwaynecarr @mwoodson

**Comment by derekwaynecarr** [comment] 2015-10-15 20:03
cc @ncdc

**Comment by jimmidyson** [comment] 2015-10-16 11:11
I think we should move the docker FS stuff into docker manager & rely on `docker info` to get free space, etc. This will use the docker abstraction over the storage backend to we don't have to do that in cadvisor.

Thoughts? @vishh @yujuhong @mvdan

**Comment by ncdc** [comment] 2015-10-16 11:15
It doesn't look like the data coming back from docker info is in raw bytes,
which could make things a bit more challenging.

**Comment by jimmidyson** [comment] 2015-10-16 11:16
Ah damn. Didn't think of that. Rubbish.

**Comment by jimmidyson** [comment] 2015-10-16 11:18
Wow that is really useless.

**Comment by mvdan** [comment] 2015-10-16 11:53
Do we have to invoke `docker`? As far as I can tell, we could import specific docker subpackages:

```
 $ go doc github.com/docker/docker/daemon/graphdriver/devmapper
package devmapper // import "github.com/docker/docker/daemon/graphdriver/devmapper"

func Init(home string, options []string, uidMaps, gidMaps []idtools.IDMap) (graphdriver.Driver, error)
func Mounted(mountpoint string) (bool, error)
func ProbeFsType(device string) (string, error)
func NewDeviceSet(root string, doInit bool, options []string, uidMaps, gidMaps []idtools.IDMap) (*DeviceSet, error)
type DevStatus struct { ... }
type DeviceSet struct { ... }
type DiskUsage struct { ... }
type Driver struct { ... }
type Status struct { ... }
```

In particular, we can probably obtain `DiskUsage` via `NewDeviceSet()` somehow.

https://github.com/docker/docker/blob/master/daemon/graphdriver/devmapper/deviceset.go#L124

This would be a lot easier to maintain and less prone to breakage across docker versions, since the `docker info` output format may change at any time.

**Comment by ncdc** [comment] 2015-10-16 11:59
You need to know the pool name, but you can get that by calling
DockerInfo() first

**Comment by jimmidyson** [comment] 2015-10-16 12:00
Sounds like a good idea, although how do we find the pool name without invoking `docker info`?

**Comment by ncdc** [comment] 2015-10-16 12:00
Or maybe just calling the docker package code can figure that out too

**Comment by jimmidyson** [comment] 2015-10-16 12:00
^^^ ah ok thanks @ncdc.

I'll have a play unless someone else is picking this up?

**Comment by ncdc** [comment] 2015-10-16 12:04
I started last night but didn't get very far. If you want it, feel free!

**Comment by jimmidyson** [comment] 2015-10-16 13:43
Pulling in the docker devicemapper package(s) would restrict cadvisor to golang 1.4 - see docker/docker#15279 for details. Pulls in some C libs.

Alternatively I could run `dmsetup status <pool>` & duplicate the calculation from https://github.com/docker/docker/blob/master/daemon/graphdriver/devmapper/deviceset.go#L2214-L2241?

Thoughts?

**Comment by ncdc** [comment] 2015-10-16 13:47
cc @vbatts @rhvgoyal

**Comment by vbatts** [comment] 2015-10-16 13:53
https://github.com/vbatts/docker/commit/f7236a195c84687edb74fec28b6c4cc98e34185c commit was not cherry-picked for 1.8.z, but will be in docker 1.9

**Comment by vbatts** [comment] 2015-10-16 13:54
(and it's docker 1.8 that didn't build with go1.5. docker-1.9 does build with go1.5)

**Comment by jimmidyson** [comment] 2015-10-16 13:54
We also have to support back to docker 1.7 (I think - maybe further) so upgrading docker package imports in cadvisor is probably not possible, unless backwards compatibility is guaranteed?

**Comment by vishh** [comment] 2015-10-16 14:54
Cadvisor uses docker info in way too many places. So I don't think depending on that is an issue. 
While we are at it we should solve this for overlay as well maybe.

**Comment by mvdan** [comment] 2015-10-16 14:59
@vishh the issue is that docker info outputs human readable info, not raw info in bytes.

**Comment by ncdc** [comment] 2015-10-16 15:00
I'm investigating using docker info to get the pool id, and then either invoking Docker's code to get the info (pending a go 1.5 fix) or using `dmsetup status <pool>`.

**Comment by rhvgoyal** [comment] 2015-10-16 15:04
I personally think that getting all the information from "docker info" makes sense. Converting Data from human readable bytes should be easy. Looks like units package in docker already provide function to convert it back. (FromHumanSize()).

https://github.com/docker/docker/blob/master/pkg/units/size.go#L63

**Comment by jimmidyson** [comment] 2015-10-16 15:05
As long as that level of accuracy is enough. I think it probably is for most cases?

**Comment by rhvgoyal** [comment] 2015-10-16 15:09
Are you referring to truncation which will happen while we converted to human readable sizes? So this will give you a lower bound of free pool space. I think this should be good enough for most use cases. If not, one can always look into changing it and trying using some function from devicemapper package.

**Comment by jimmidyson** [comment] 2015-10-16 15:21
@rhvgoyal Sadly the human size regex doesn't take into account decimals (https://github.com/docker/docker/blob/master/pkg/units/size.go#L34) even though the inverse does format with decimals (https://github.com/docker/docker/blob/master/pkg/units/size.go#L54). But parsing is pretty easy tbh so we could just do that in cadvisor (although that bug in docker should probably be fixed too).

**Comment by ncdc** [comment] 2015-10-16 15:31
I just tested on Kube master. It turns out that capacity is being reported when the Docker storage driver is devicemapper, but I don't believe the reported data is correct.

I am seeing that cadvisor is reporting usage=17426235392, capacity=29790838784, which lines up with my device for `/`:

```
/dev/mapper/vg_vagrant-lv_root   29092616  17017808   10830668  62% /
```

Meanwhile, `docker info` reports this (yeah yeah, I'm still using loopback on my VM :smile:):

```
Storage Driver: devicemapper
 Pool Name: docker-253:1-130513-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.731 GB
 Data Space Total: 107.4 GB
 Data Space Available: 12.36 GB
 Metadata Space Used: 8.663 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
```

**Comment by ncdc** [comment] 2015-10-16 16:02
I'm not sure querying for the filesystem that cadvisor has labeled "docker-images" is the best way to do this going forward. It might make more sense to move the image storage query into something that isn't filesystem-specific. That way, we can detect the driver and decide the right path (query devicemapper vs filesystem vs ...). WDYT?

**Comment by jimmidyson** [comment] 2015-10-16 16:02
Got the `docker info` way working but it's incredibly hacky.

So one option would be to carry @vbatts 1.9 patch in cadvisor & kubernetes/openshift so we can use the devicemapper packages directly?

I'd also propose removing the `docker-images` label from the fs code in cadvisor & moving the get docker size to the docker handler package. This way we can hopefully use docker packages directly to get storage backend info rather than trying to guess the correct fs as it is doing now. This is really fragile & hard to extend. This would be a breaking change but one I think is necessary. We'd have to make the necessary changes in kubernetes image GC too.

**Comment by vishh** [comment] 2015-10-16 18:48
@mvdan: I meant retrieving the storage driver info using `docker info` and performing capacity and usage calculations in cAdvisor. Sorry if that was not clear.
@ncdc: +1 for moving towards a pluggable model for managing docker images partition.
I prefer not depending on docker's API for getting usage and capacity for a few reasons.
1. Backwards compatibility. cAdvisor currently works with older versions of docker as well.
2. I assume we can re-use the `dmsetup` utility based approach for calculating container's fs usage as well. This will be useful for monitoring and disk scheduling in Kubernetes, until we have support for disk quota.

**Comment by vishh** [comment] 2015-10-16 18:51
> I'd also propose removing the docker-images label from the fs code in cadvisor & moving the get docker size to the docker handler package. This way we can hopefully use docker packages directly to get storage backend info rather than trying to guess the correct fs as it is doing now. This is really fragile & hard to extend. This would be a breaking change but one I think is necessary. 

A huge +1. Why would this be a breaking change? Kubelet uses the `Manager` interface abstractions and I assume these changes are internal to cAdvisor.

**Comment by ncdc** [comment] 2015-10-16 18:55
> I assume we can re-use the dmsetup utility based approach for calculating container's fs usage as well. 

Maybe... I'll defer to @vbatts @rhvgoyal here. I just did a quick test running the busybox image and making a few copies of /bin/busybox inside the container. Here are the results:

```
# before making any copies
vagrant@f22:~ sudo dmsetup status docker-253:0-33713995-7a20304c351953c720074ff1eda85ee21e11d0bb2bdbe8d358480377ad073ce1
0 209715200 thin 138240 209715199
# after making a few copies
vagrant@f22:~ sudo dmsetup status docker-253:0-33713995-7a20304c351953c720074ff1eda85ee21e11d0bb2bdbe8d358480377ad073ce1
0 209715200 thin 142336 209715199
```

You can see that one number increased: 138240 to 142336. This seems promising.

**Comment by jimmidyson** [comment] 2015-10-16 18:58
Yeah that is doing the right thing, but that's then different if we're using thin-pool LVM. And then there's overlay to think of, etc.

I'm feeling that we're going to be duplicating a reasonable amount of the docker storage backend stuff if we go down this route. I'd rather reuse the docker code if possible for maintenance & compatibility if at all possible.

**Comment by ncdc** [comment] 2015-10-16 19:00
I think this is a thin-pool LVM, unless I did something wrong when I ran `docker-storage-setup` (this is a brand new VM with `/dev/sdb` dedicated to Docker storage).

**Comment by ncdc** [comment] 2015-10-16 19:01
But I agree it sure would be nice just to get this info from somewhere else instead of having to reinvent the wheel.

**Comment by rhvgoyal** [comment] 2015-10-16 19:01
As per the thin target documentation first field after "thin" depicts, `nr mapped sectors`. So it will tell you how many sectors are actually mapped/used for this thin device.

**Comment by jimmidyson** [comment] 2015-10-16 19:04
My output is different to yours - what's the difference between our setups I wonder? I'm direct LVM thin-pool (definitely, maybe).

```
$ dmsetup status docker-253:4-2646052-pool
0 409534464 thin-pool 49091 8247/4161600 251685/3199488 - rw no_discard_passdown queue_if_no_space
```

**Comment by vishh** [comment] 2015-10-16 19:04
If we use `docker info` for this purpose, how will we handle container filesystem usage measurements?

**Comment by vbatts** [comment] 2015-10-16 19:04
reusing docker code will only get you so far here too. And you may get
stuck. Overlay and btrfs don't give you this detailed of information
either. Overlay and vfs, you'd have to get `df <docker root dir>`, and
btrfs has different approaches depending on the version of btrfs-progs
available.

**Comment by jimmidyson** [comment] 2015-10-16 19:05
@vishh That is a different question - one we need to answer, just not now I don't think.

**Comment by ncdc** [comment] 2015-10-16 19:05
@jimmidyson I was looking at a container; you're looking at the entire pool. I have the thin-pool output as well:

```
docker-docker--pool: 0 53624832 thin-pool 7 16/17408 161/52368 - rw discard_passdown queue_if_no_space
```

**Comment by jimmidyson** [comment] 2015-10-16 19:05
@ncdc OK cool - now I understand! So there we have the answer to @vishh's question about how to get container filesystem sizes as well - nice.

**Comment by rhvgoyal** [comment] 2015-10-16 19:06
i think we should try to get all the information about images/containers using docker API.

**Comment by jimmidyson** [comment] 2015-10-16 19:07
@rhvgoyal I don't think you can get the level of info we need from the docker API: container filesystem size, used, available, etc.

**Comment by ncdc** [comment] 2015-10-16 19:10
I want to state, at least for my own understanding, what I believe to be the problems we are trying to address:

- determine the used, available, total capacity of the location where Docker is storing images
  - for e.g. Kubernetes to make a determination when it needs to GC some images
- determine the used, available, total capacity of a container's file system
  - is this just the unique COW/overlay delta? or something else?
  - for ???

Is this correct?

**Comment by rhvgoyal** [comment] 2015-10-16 19:16
@jimmidyson I think this information is dependent on graph driver and some of it is run time information. 

In general, I think we should export all the needed information using "docker-inspect" and let higher layers use it.

For example, for devicemapper, you can get some information in "GraphDriver" section. For devicemapper it is exporting "DeviceSize" which should tell you the total virtual size of container.

For space used, I feel you should start container and do "docker exec df /".

**Comment by jimmidyson** [comment] 2015-10-16 19:16
@ncdc :white_check_mark: That's my understanding too. The immediate use case is definitely the info on the file system where Docker stores images to trigger image GC by the kubelet. Individual container fs info is a nice to have - use case to help identify containers that are taking up a lot of space but this is a future enhancement in my eyes.

**Comment by jimmidyson** [comment] 2015-10-16 19:23
@rhvgoyal While I like the idea of `docker exec` or equivalent via `setns` but we have to be careful not to interfere with cleaning up containers. We did the old `setns` trick to get network metrics & found this sometimes messed up cleaning up docker containers as we're switching into container namespaces quite regularly to gather this data. We switched to raw host `/proc` tricks in the end & works great without any of these problems.

Also can we rely on `DeviceSize` (or alternative for different backends) being consistent between storage backends for retrieval? `DeviceSize` seems to be different to what `dmsetup status` shows me so I'm a little wary about that too tbh (although could be me not understanding something).

**Comment by vbatts** [comment] 2015-10-16 19:24
@ncdc correct. Like I said, while this could be plumbed through docker like @rhvgoyal is saying, it has not been. It is very determined by the underlying CoW setup, and would leave you much more flexible to access the storage directly.

**Comment by rhvgoyal** [comment] 2015-10-16 19:35
@jimmidyson DeviceSize gives you the virtual size of thin device  in case of devicemapper. That is either 10G or 100G out of box depending on docker version you are running.

**Comment by rhvgoyal** [comment] 2015-10-16 19:38
@jimmidyson If you do "dmsetup table <thin-device>, it will show you following.

`docker-253:1-2616453-5ea3100b3d4e0342d6154d68197fa339cf411132e6ab424dfdba9dc289e0253f: 0 209715200 thin 253:4 292`

Here 209715200 is last sector. Multiply it by 512, and you have to device size in bytes. Same as reported by DeviceSize in docker-inspect.

**Comment by jimmidyson** [comment] 2015-10-16 19:39
@rhvgoyal Now that makes sense - thanks!

**Comment by rhvgoyal** [comment] 2015-10-16 19:47
@jimmidyson Also DeviceSize is specific to devicemapper. I had introuced it because we were writing some tools so that we could use this information and mount image/container separately and inspect it. `atomic mount` etc. But some of the use cases were racy w.r.t docker operations (container deletion etc).

Now people are working on aother tool and try to make it less racy. Basically move COW layer management in a separate tool and let everybody talk to that tool to mount/unmount. Once that tool is
up and running, there is a possibility that you can call into that one and mount storage and inspect it (including for size).

But I guess this will also have some interference w.r.t container deletion as if container is being deleted which you have storage mounted, then deletion will fail. Or storage will be left behind with nobody to clean it up.

**Comment by jimmidyson** [comment] 2015-10-16 19:57
So what's the consensus on a way forward for this? Easiest for now is probably: Refactor to retrieve storage backend from `docker info`. Support `devicemapper` via `dmsetup status` parsing for Docker root & container FS (as future work). Should get us where we need?

**Comment by rhvgoyal** [comment] 2015-10-16 20:02
@jimmidyson So you want to look at "dmsetup status <thin-device>" to determine the fs size of container? Give it a try, may be it will work. Otherwise use "docker exec". BTW, docker-inspect gives
you the name of the device backing container. So it will make life little easy for you to figure out which thin device belongs to container root.

`    "GraphDriver": {
        "Name": "devicemapper",
        "Data": {
            "DeviceId": "292",
            "DeviceName": "docker-253:1-2616453-5ea3100b3d4e0342d6154d68197fa339cf411132e6ab424dfdba9dc289e0253f",
            "DeviceSize": "107374182400"
        }`

**Closed** 2015-10-21 14:05 UTC
