### ISSUE TITLE
cAdvisor stops monitoring after a couple of minutes

### ISSUE THREAD

**Issue by aelmehra** [google/cadvisor#1614] opened 2017-03-13 17:48 UTC
I have about 20 containers that cAdvisor is monitoring but after a couple of minutes most of the metrics returned are 0.

Navigating to http://NODE:8080/api/v2.0/stats/CONTAINER?type=docker&count=1, returns:

{"/system.slice/var-lib-docker-containers-a20a4877bdb8407be04a1d660f1b9b2bc11ad93255d8983666352b19dabf31af-shm.mount":[{"timestamp":"2017-03-13T17:45:06.429270533Z","has_cpu":true,"cpu":{"usage":{"total":0,"per_cpu_usage":[0,0,0,0],"user":0,"system":0},"cfs":{"periods":0,"throttled_periods":0,"throttled_time":0},"load_average":0},"has_diskio":true,"diskio":{},"has_memory":true,"memory":{"usage":0,"cache":0,"rss":0,"swap":0,"working_set":0,"failcnt":0,"container_data":{"pgfault":0,"pgmajfault":0},"hierarchical_data":{"pgfault":0,"pgmajfault":0}},"has_network":true,"network":{"interfaces":[{"name":"eth0","rx_bytes":1032565,"rx_packets":6270,"rx_errors":0,"rx_dropped":0,"tx_bytes":2481542,"tx_packets":4757,"tx_errors":0,"tx_dropped":0},{"name":"eth1","rx_bytes":670070,"rx_packets":6295,"rx_errors":0,"rx_dropped":0,"tx_bytes":6364393,"tx_packets":5869,"tx_errors":0,"tx_dropped":0}],"tcp":{"Established":0,"SynSent":0,"SynRecv":0,"FinWait1":0,"FinWait2":0,"TimeWait":0,"Close":0,"CloseWait":0,"LastAck":0,"Listen":0,"Closing":0},"tcp6":{"Established":0,"SynSent":0,"SynRecv":0,"FinWait1":0,"FinWait2":0,"TimeWait":0,"Close":0,"CloseWait":0,"LastAck":0,"Listen":0,"Closing":0}},"has_filesystem":true,"filesystem":[{"device":"/dev/mapper/cl-root","type":"vfs","capacity":53660876800,"usage":2732199936,"base_usage":2732154880,"available":0,"has_inodes":false,"inodes":0,"inodes_free":0,"reads_completed":0,"reads_merged":0,"sectors_read":0,"read_time":0,"writes_completed":0,"writes_merged":0,"sectors_written":0,"write_time":0,"io_in_progress":0,"io_time":0,"weighted_io_time":0}],"has_load":false,"load_stats":{"nr_sleeping":0,"nr_running":0,"nr_stopped":0,"nr_uninterruptible":0,"nr_io_wait":0},"has_custom_metrics":false}]}

OS: Centos 7
Kernel: 3.10.0-514.10.2.el7.x86_64
Docker version: 17.03.0-ce, build 60ccb22
cAdvisor version: v0.24.1

**Comment by dashpole** [comment] 2017-03-20 17:46
duplicate of #1572.  The fix, #1573 is in v0.25.0

**Closed by dashpole** 2017-03-20 17:46 UTC
Labels: closed/duplicate
