### ISSUE TITLE
/api/v1.2/docker/ get json aliases can't macth using command data

### ISSUE THREAD

**Issue by zhaoguoxin** [google/cadvisor#1435] opened 2016-08-23 02:18 UTC
## I use /api/v1.2/docker . i get json once .the data aliases

``` json
"aliases": [
      "myni",
      "265a2ae1a4b8bd04bbae73400191790f5e7153cb6caabc014e8ad3aa89679f6c"
    ]
```

i use docker rename myni updatemyni 

then ,i use /api/v1.2/docker/.  but the json "aliases": [
      "myni",
      "265a2ae1a4b8bd04bbae73400191790f5e7153cb6caabc014e8ad3aa89679f6c"
    ],
i am so confused, why the aliases is not updatemyni
but i use docker ps -a  the data is updatemyni

**Comment by dashpole** [comment] 2017-03-17 00:16
If I understand you correctly, I believe this is a duplicate of #977.  Feel free to post a PR that fixes this, but we do not currently support container renaming.

**Closed by dashpole** 2017-03-17 00:16 UTC
Labels: closed/duplicate, kind/support
