### ISSUE TITLE
cadvisor and influxdb integration

### ISSUE THREAD

**Issue by mboussaa** [google/cadvisor#675] opened 2015-05-04 15:50 UTC
I want to access to the gathered data from cadvisor through influxdb here my docker configurations:
```
//for cadvisor
docker run     
--volume=/:/rootfs:ro     
--volume=/var/run:/var/run:rw     
--volume=/sys:/sys:ro     
--volume=/var/lib/docker/:/var/lib/docker:ro     
--publish=8080:8080     
--detach=true     
--name=cadvisorDB     
google/cadvisor:latest     
-storage_driver=influxdb     
-storage_driver_host=127.0.0.1:8086
-storage_driver_db=databaseName

//for InfluxDB
docker run 
-d 
-p 8083:8083 
-p 8086:8086 
--expose 8090 
--expose 8099 
tutum/influxdb
//and I created manually the databse through the WEB UI at localhost:8083   
with the name "databaseName"`
```
So once I start both containers, I go to the influxDB to explore the data (by making a simple query). An error appears saying that there is no data

**Comment by vmarmol** [comment] 2015-05-04 17:27
Can you run cAdvisor with `--logtostderr --v=2` and provide the outputs?

**Comment by mboussaa** [comment] 2015-05-04 18:39
![untitled](https://cloud.githubusercontent.com/assets/5878565/7459503/c286c38c-f29c-11e4-90aa-c5851d9cc9d0.png)

Yes I did that and as you can see, cAdvisor is working very well however, it does not dump data to the specified db in influxdb.

If I run something like "select count(*) from stats" in influxdb Web UI it shows " ERROR : can't find series : stats"

I don't know if the problem is more clear.

**Comment by vmarmol** [comment] 2015-05-04 18:44
Sorry, maybe I wasn't clear :) I wanted to take a look at the cAdvisor logs to see if there were any errors in sending the data.

Can you also do a `list series` in InfluxDB?

**Comment by mboussaa** [comment] 2015-05-04 19:08
Thank you for the clarification.
When trying to get logs : 
![33](https://cloud.githubusercontent.com/assets/5878565/7460139/412394b4-f2a1-11e4-9367-8b854810d625.png)
For influx DB :
![22](https://cloud.githubusercontent.com/assets/5878565/7460140/44610274-f2a1-11e4-9bb0-3c2a11679daf.png)

NB: I am using a VirtualBoxVM with Ubunto as a virtual machine. That may help to understand the problem.

**Comment by mboussaa** [comment] 2015-05-04 19:16
I0504 17:59:04.438751 00001 storagedriver.go:90] Using backend storage type "influxdb"
I0504 17:59:04.442380 00001 storagedriver.go:94] Caching 60 stats in memory
I0504 17:59:04.442776 00001 manager.go:106] cAdvisor running in container: "/docker/91e3c58b9a69174c65244a774a0ee01f32820e3bcf162561922a8350d9484be4"
I0504 17:59:04.445607 00001 fs.go:87] Filesystem partitions: map[/dev/mapper/ubuntu--vg-root:{mountpoint:/rootfs major:252 minor:0} /dev/sda1:{mountpoint:/rootfs/boot major:8 minor:1}]
I0504 17:59:04.453717 00001 machine.go:223] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I0504 17:59:04.469639 00001 manager.go:127] Machine: {NumCores:1 CpuFrequency:2587640 MemoryCapacity:10290925568 MachineID: SystemUUID:E8E478D3-3092-49A8-A802-13BA926862AE BootID:20331896-31b4-466a-8684-ae8cbb954470 Filesystems:[{Device:/dev/mapper/ubuntu--vg-root Capacity:22072389632} {Device:/dev/sda1 Capacity:246755328}] DiskMap:map[252:0:{Name:dm-0 Major:252 Minor:0 Size:22561161216 Scheduler:none} 252:1:{Name:dm-1 Major:252 Minor:1 Size:10536091648 Scheduler:none} 8:0:{Name:sda Major:8 Minor:0 Size:33388118016 Scheduler:deadline}] NetworkDevices:[{Name:eth0 MacAddress:08:00:27:19:78:32 Speed:1000 Mtu:1500}] Topology:[{Id:0 Memory:10290925568 Cores:[{Id:0 Threads:[0] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Data Level:1} {Size:6291456 Type:Data Level:2}]}] Caches:[]}]}
I0504 17:59:04.477555 00001 manager.go:134] Version: {KernelVersion:3.16.0-31-generic ContainerOsVersion:Buildroot 2014.02 DockerVersion:1.6.0 CadvisorVersion:0.12.0}
I0504 17:59:04.509139 00001 factory.go:226] Registering Docker factory
I0504 17:59:04.524481 00001 factory.go:60] Registering Raw factory
I0504 17:59:04.525402 00001 manager.go:872] Started watching for new ooms in manager
E0504 17:59:04.525517 00001 manager.go:199] Failed to start OOM watcher, will not get OOM events: exec: "journalctl": executable file not found in $PATH
I0504 17:59:04.544673 00001 manager.go:212] Starting recovery of all containers
I0504 17:59:04.582335 00001 manager.go:217] Recovery completed
I0504 17:59:04.597763 00001 cadvisor.go:90] Starting cAdvisor version: "0.12.0" on port 8080
E0504 18:00:04.562568 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:01:04.581246 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:02:04.572020 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:03:04.579496 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:04:04.579458 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:05:04.595141 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:06:04.603950 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:07:04.608570 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:08:05.565142 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:09:05.573991 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:10:05.581251 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:11:05.603416 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:12:05.583855 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:13:05.598008 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused
E0504 18:14:05.604288 00001 memory.go:84] failed to write stats to influxDb - Post http://127.0.0.1:8086/db/databaseName/series?u=root&p=root&time_precision=u: dial tcp 127.0.0.1:8086: connection refused

**Comment by vmarmol** [comment] 2015-05-04 20:01
It looks like we're not able to connect to InfluxDB. The issue is that you're pointing to localhost for InfluxDB, that resolves to the container itself which is not running InfluxDB. You'll need to give it the IP of the host itself.

**Comment by mboussaa** [comment] 2015-05-04 21:29
+1. In fact, yes that's true. I should write the Host IP. It works right now :) That's great. I am planning to link these data to grafana in order to display the graphs of each query. 
Is there any documentation of the data structure? such as columns names, definition...

**Comment by vmarmol** [comment] 2015-05-05 20:54
Sadly the best we have is the [code](https://github.com/google/cadvisor/blob/master/storage/influxdb/influxdb.go#L38) for now. Just filed #681 to add that.

Closing this issue, but feel free to open a new issue if you run into any problems :)

**Closed by vmarmol** 2015-05-05 20:54 UTC

**Comment by mboussaa** [comment] 2015-05-07 13:23
Yes, I think it is very important to document the data structure that does store cAdvisor. In the testing community, these values are very useful for evaluating test suites. Any way, I making some experiments using cAdvisor. For sure, I will open many new issues :)

**Comment by vmarmol** [comment] 2015-05-07 15:08
Great! We're happy to see what's missing and what's harder than it should be :)
