### ISSUE TITLE
container_start_time_seconds resets randomly

### ISSUE THREAD

**Issue by moreiramarti** [google/cadvisor#1879] opened 2018-01-31 08:28 UTC
Hello,

Recently I faced some resets on container_start_time_seconds metric but when I checked my container with docker ps command, it show no reboot of the container.

#1607 already mention this problem (I'm using v0.28.3) so I thought it was solve but I still have this issue.

Thank you,
Martinho MOREIRA

**Comment by jeroenhendricksen** [comment] 2018-02-04 10:26
I can confirm this behavior. After cadvisor was failing, I restarted cadvisor, and all the container_start_time_seconds for the host were cadvisor was running were reset. The output differs from that of `docker ps` which I would not expect. It looks like this issue is related: https://github.com/google/cadvisor/issues/1607

Docker version: 18.01.0-ce
Cadvisor version: v0.28.3 
Prometheus: v1.7.2

**Comment by hiscal2015** [comment] 2018-02-07 03:08
looks it has not been merged.

**Comment by moreiramarti** [comment] 2018-03-01 10:13
Does anyone know when it will be merged?

**Comment by dashpole** [comment] 2018-03-01 17:47
https://github.com/google/cadvisor/pull/1806 was merged, and is in the most recent release.

**Closed by dashpole** 2018-03-01 17:47 UTC
