### ISSUE TITLE
metrics process empty at dashboard

### ISSUE THREAD

**Issue by Siddharthav1** [google/cadvisor#2862] opened 2021-05-05 05:40 UTC
Hello,
I am using the cadvisor to collect the container health data.Here, I am using the below command to run the cadvisor:

```
    sudo docker run --volume=/:/rootfs:ro --volume=/var/run:/var/run:ro --volume=/sys:/sys:ro -- 
    volume=/var/lib/docker/:/var/lib/docker:ro --volume=/dev/disk/:/dev/disk:ro --publish=8080:8080 --detach=true -- 
    name=cadvisor google/cadvisor:latest
```
But, the issue is I am getting the CPU and memory related data but it is faillig to collect the "container_cpu_load_average_10s" I am getting this value as "zero".

And also in dashboard, the processes are not seen. It says **"no precesses found"**.

![image](https://user-images.githubusercontent.com/59814967/117100756-3458d700-ad92-11eb-9c6a-b83917d398d8.png)

Can anybody suggest what is the issue here?

regards,
Siddhartha V

**Comment by iwankgb** [comment] 2021-05-07 16:34
This is de facto a duplicate of #2860.

**Closed by iwankgb** 2021-05-07 16:34 UTC
