### ISSUE TITLE
cadvisor should not add flags everywhere.

### ISSUE THREAD

**Issue by Random-Liu** [google/cadvisor#1417] opened 2016-08-10 07:50 UTC
Currently, a lot of different packages cadvisor are exposing flags, such as:
`boot_id_file`: https://github.com/google/cadvisor/blob/bbe54c0a1037111f3982a1754486c935a5d813c0/machine/info.go#L35
`machine_id_file`:
https://github.com/google/cadvisor/blob/bbe54c0a1037111f3982a1754486c935a5d813c0/machine/info.go#L34
`docker_root`:
https://github.com/google/cadvisor/blob/8fa31bc6276eabb8e276a0925fe47bfcea5cc36c/container/docker/factory.go#L42
`housekeeping_interval`:
https://github.com/google/cadvisor/blob/b5d86a72889f4a5d9bdf3416c759c809444ee448/manager/container.go#L46

And a lot more...

If these packages are used by another project, these flags will be introduced unexpectedly.
For node conformance test, we have to use original golang flag package to keep `ginkgo flags` and `go test flags`, but the cadvisor flags will be added unexpectedly and there is no way to eliminate them.

Cadvisor should deal with flags in a separate package to avoid this.

/cc @vishh @timstclair @dchen1107

**Comment by timstclair** [comment] 2016-08-10 17:46
Duplicate of https://github.com/google/cadvisor/issues/1175
xRef https://github.com/kubernetes/kubernetes/issues/19432

**Closed by timstclair** 2016-08-10 17:46 UTC

**Comment by Random-Liu** [comment] 2016-08-12 18:55
@timstclair Cool thanks! Hope we can clean up this someday. :)
