### ISSUE TITLE
when the cadvisor is running, other docker containers cannot be removed in the same host

### ISSUE THREAD

**Issue by siuwwong5** [google/cadvisor#1863] opened 2018-01-15 08:19 UTC
[root@hkgcvdv00396 docker]# docker ps -a
CONTAINER ID        IMAGE                                                                  COMMAND                  CREATED             STATUS              PORTS                    NAMES
7ca562c97638        google/cadvisor:latest                                                 "/usr/bin/cadvisor -l"   28 hours ago        Up 28 hours         0.0.0.0:8088->8080/tcp   cadvisor
cf50ba0eef93        artifact.oocl.com/wls_iris4_shp/wls_dom_shpfe:23.9.0.0.064-12.2.1.24   "run.sh"                 4 days ago          Dead                                         WLS_DOM_SHPFE
cf584f944d63        artifact.oocl.com/wls_iris4_shp/wls_dom_shp:23.9.0.0.064-12.2.1.24     "run.sh"                 4 days ago          Dead                                         WLS_DOM_SHP
f6adb9087c34        artifact.oocl.com/wls_iris4_shp/wls_dom_shpbe:23.9.0.0.064-12.2.1.24   "run.sh"                 4 days ago          Dead                                         WLS_DOM_SHPBE
57eb8a537518        artifact.oocl.com/wls_iris4_shp/wls_dom_shpv:23.9.0.0.064-12.2.1.24    "run.sh"                 4 days ago          Dead                                         WLS_DOM_SHPV
[root@hkgcvdv00396 docker]# docker rm cf584f944d63
Error response from daemon: Unable to remove filesystem for cf584f944d63ab4c12b64a67721e03321e9530d15ab02e75fbfaa0c7502f123b: remove /var/lib/docker/containers/cf584f944d63ab4c12b64a67721e03321e9530d15ab02e75fbfaa0c7502f123b/shm: device or resource busy
[root@hkgcvdv00396 docker]#

**Comment by siuwwong5** [comment] 2018-01-15 08:26
[root@hkgcvdv00396 docker]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.3 (Maipo)
[root@hkgcvdv00396 docker]# docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

**Comment by dashpole** [comment] 2018-01-16 17:57
closing as duplicate of https://github.com/google/cadvisor/issues/771.  There are some workarounds posted there.  See if any of those work for you.

**Closed by dashpole** 2018-01-16 17:57 UTC
