### ISSUE TITLE
[Ububtu 14.04] Failed to get system UUID: open /proc/device-tree/vm,uuid: no such file or directory

### ISSUE THREAD

**Issue by svenmueller** [google/cadvisor#924] opened 2015-10-17 10:40 UTC
Hi,

When using the provided `docker run` example i'm getting this error:

``` bash
$ sudo docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest
```

Then the logs shows the following:

``` bash
$ docker logs cadvisor
E1017 10:37:14.214073 00001 machine.go:87] Failed to get system UUID: open /proc/device-tree/vm,uuid: no such file or directory
```

i also tried adding `--privileged=true` and ended up with the same result. Any idea how this can be solved?

**Comment by svenmueller** [comment] 2015-10-22 08:01
anyone else having the same issue? what could cause this error log?

**Comment by jimmidyson** [comment] 2015-10-22 08:19
Does it affect cadvisor functionality or is it just an error message?

**Comment by svenmueller** [comment] 2015-10-22 08:33
it seems to work (beside that we are seeing #771). but there are no other logs shown..so logging might be affected?

**Comment by jimmidyson** [comment] 2015-10-22 08:39
Can you share the full log? Unless you change the log level with e.g. `--v=8` then logs are pretty quiet usually.

I think the problem is we don't check the relevant files from the mounted host rootfs, but rather the container root fs.

**Comment by svenmueller** [comment] 2015-10-22 12:47
how can i set the native flag `--v=8` when using `docker run...`?

**Comment by jimmidyson** [comment] 2015-10-22 12:50
Just append it to the docker run command:

    docker run .... google/cadvisor:latest --v=8

**Comment by svenmueller** [comment] 2015-10-22 12:58
Thx. I just tried it. But there is no change in the logged data:

```bash
$ docker logs cadvisor
E1022 12:58:03.536020 00001 machine.go:87] Failed to get system UUID: open /proc/device-tree/vm,uuid: no such file or directory
```

**Comment by svenmueller** [comment] 2015-10-22 13:00
this is the command i'm using

```bash
docker run --net bridge -m 0b --detach=true -p 9090:8080 -v /var/run:/var/run:rw -v /sys:/sys:ro  --name cadvisor google/cadvisor:latest --v=8\
```

**Comment by osallou** [comment] 2015-10-30 08:59
Same issue (same error message) on a Debian 8.1 on Amazon EC2, and can't access interface.

**Comment by svenmueller** [comment] 2015-11-14 12:07
i even can't see the full logs using `--v=8`

**Comment by dashpole** [comment] 2017-03-16 18:59
closing as outdated.  Please open a new issue with a repro on a recent release if the problem persists.

**Closed by dashpole** 2017-03-16 18:59 UTC
