### ISSUE TITLE
container_cpu_user_seconds_total miss sth

### ISSUE THREAD

**Issue by Cas-pian** [google/cadvisor#1721] opened 2017-08-17 04:52 UTC
cadvisor v0.26.1 somtimes container_cpu_user_seconds_total doesn't contains any container info, showed by the graph below.
![image](https://user-images.githubusercontent.com/5690854/29396462-9da0cd9c-834a-11e7-9fc9-a8c3691d9d8d.png)  

v0.24.1 is ok with this metric.   
Any reply is appreciated. Thanks!

**Comment by dashpole** [comment] 2017-08-17 16:17
duplicate of #1704 
Prometheus changed the way they treat missing metrics, so we havent known about it until recently.

**Closed by dashpole** 2017-08-17 16:17 UTC
