### ISSUE TITLE
Wrong `container_fs_io_current` on /metrics endpoint

### ISSUE THREAD

**Issue by fabxc** [google/cadvisor#1412] opened 2016-08-05 12:58 UTC
See prometheus/prometheus#1863

**Comment by grobie** [comment] 2016-08-05 18:30
Duplicate of #1404.

**Comment by fabxc** [comment] 2016-08-05 21:01
My bad, can be closed then.

**Comment by barnettZQG** [comment] 2016-08-08 10:41
Can you explain what time can solve this issue? thank you

**Comment by jimmidyson** [comment] 2016-08-08 10:43
Dupe of #1404

**Closed** 2016-08-08 10:42 UTC
