### ISSUE TITLE
W0122 Cannot read vendor id correctly, set empty - Pi 4B1.5

### ISSUE THREAD

**Issue by nickytd** [google/cadvisor#3238] opened 2023-01-22 08:48 UTC
Hi 
[GetCPUVendorID](https://github.com/google/cadvisor/blob/5377d335a9eb652d152325d25f25be1c9cc638f7/machine/machine.go#L60) dumps constantly a warning message "Cannot read vendor id correctly, set empty." on Raspberry Pi 4 Model B Rev 1.5
`proc/cpuinfo` is
```
processor	: 3
BogoMIPS	: 108.00
Features	: fp asimd evtstrm crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3
```

And the implementation fails to match the regex ```vendor_id\s*:\s*(\w+)```
Imho we can either reduce the warning message occurrence or support the cpu type (if possible)
Thanks

**Comment by fede843** [comment] 2023-01-26 11:22
same

**Comment by jlkDE** [comment] 2023-01-28 12:05
Sounds like a duplicate of https://github.com/google/cadvisor/issues/3160 - I experience the same annoyance by the way.

**Closed** 2023-02-26 03:41 UTC
