### ISSUE TITLE
how can i get the "container_fs_io_current"? why is always 0

### ISSUE THREAD

**Issue by Chentongxuedefanhua** [google/cadvisor#1404] opened 2016-08-02 01:32 UTC
why the 'fs_stats' of cAdvisor's /metrics is always 0,like this:
![qq 20160801125300](https://cloud.githubusercontent.com/assets/18111540/17314068/042bd968-5894-11e6-984a-6938a380d0ed.png)

**Comment by barnettZQG** [comment] 2016-08-04 14:57
I also got the info about io is  always 0 from cadvisor and prometheus.

**Comment by barnettZQG** [comment] 2016-08-08 10:46
Can you explain what time can solve this issue? thank you

**Comment by skebo** [comment] 2016-08-30 21:55
yes, all my blkio stats for containers are all 0 as well.  I've tested on ubuntu 16.04  (docker v1.6 through 1.12 w/aufs) and RHEL 7.2 (docker 1.11 and 1.12 w/devicemapper) with my I/O scheduler set to cfq and I still get all zeroes. 

Here is the /validate from my ubuntu box:
```cAdvisor version: 0.23.8

OS version: Alpine Linux v3.2

Kernel version: [Supported and recommended]
	Kernel version is 4.4.0-34-generic. Versions >= 2.6 are supported. 3.0+ are recommended.


Cgroup setup: [Supported and recommended]
	Available cgroups: map[freezer:1 net_cls:1 perf_event:1 hugetlb:1 pids:1 cpuset:1 cpuacct:1 memory:1 devices:1 net_prio:1 cpu:1 blkio:1]
	Following cgroups are required: [cpu cpuacct]
	Following other cgroups are recommended: [memory blkio cpuset devices freezer]
	Hierarchical memory accounting enabled. Reported memory usage includes memory used by child containers.


Cgroup mount setup: [Supported and recommended]
	Cgroups are mounted at /sys/fs/cgroup.
	Cgroup mount directories: blkio cpu cpu,cpuacct cpuacct cpuset devices freezer hugetlb memory net_cls net_cls,net_prio net_prio perf_event pids systemd 
	Any cgroup mount point that is detectible and accessible is supported. /sys/fs/cgroup is recommended as a standard location.
	Cgroup mounts:
	cgroup /sys/fs/cgroup/systemd cgroup ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
	cgroup /sys/fs/cgroup/hugetlb cgroup ro,nosuid,nodev,noexec,relatime,hugetlb 0 0
	cgroup /sys/fs/cgroup/net_cls,net_prio cgroup ro,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
	cgroup /sys/fs/cgroup/cpu,cpuacct cgroup ro,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
	cgroup /sys/fs/cgroup/pids cgroup ro,nosuid,nodev,noexec,relatime,pids 0 0
	cgroup /sys/fs/cgroup/memory cgroup ro,nosuid,nodev,noexec,relatime,memory 0 0
	cgroup /sys/fs/cgroup/freezer cgroup ro,nosuid,nodev,noexec,relatime,freezer 0 0
	cgroup /sys/fs/cgroup/blkio cgroup ro,nosuid,nodev,noexec,relatime,blkio 0 0
	cgroup /sys/fs/cgroup/cpuset cgroup ro,nosuid,nodev,noexec,relatime,cpuset 0 0
	cgroup /sys/fs/cgroup/perf_event cgroup ro,nosuid,nodev,noexec,relatime,perf_event 0 0
	cgroup /sys/fs/cgroup/devices cgroup ro,nosuid,nodev,noexec,relatime,devices 0 0
	cgroup /rootfs/sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
	cgroup /rootfs/sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
	cgroup /rootfs/sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
	cgroup /rootfs/sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
	cgroup /rootfs/sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
	cgroup /rootfs/sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
	cgroup /rootfs/sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
	cgroup /rootfs/sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
	cgroup /rootfs/sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
	cgroup /rootfs/sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
	cgroup /rootfs/sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
	cgroup /rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/systemd cgroup ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
	cgroup /rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/hugetlb cgroup ro,nosuid,nodev,noexec,relatime,hugetlb 0 0
	cgroup /rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/net_cls,net_prio cgroup ro,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
	cgroup /rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/cpu,cpuacct cgroup ro,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
	cgroup /rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/pids cgroup ro,nosuid,nodev,noexec,relatime,pids 0 0
	cgroup /rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/memory cgroup ro,nosuid,nodev,noexec,relatime,memory 0 0
	cgroup /rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/freezer cgroup ro,nosuid,nodev,noexec,relatime,freezer 0 0
	cgroup /rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/blkio cgroup ro,nosuid,nodev,noexec,relatime,blkio 0 0
	cgroup /rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/cpuset cgroup ro,nosuid,nodev,noexec,relatime,cpuset 0 0
	cgroup /rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/perf_event cgroup ro,nosuid,nodev,noexec,relatime,perf_event 0 0
	cgroup /rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/devices cgroup ro,nosuid,nodev,noexec,relatime,devices 0 0
	cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
	cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
	cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
	cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
	cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
	cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
	cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
	cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
	cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
	cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
	cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/systemd cgroup ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/hugetlb cgroup ro,nosuid,nodev,noexec,relatime,hugetlb 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/net_cls,net_prio cgroup ro,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/cpu,cpuacct cgroup ro,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/pids cgroup ro,nosuid,nodev,noexec,relatime,pids 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/memory cgroup ro,nosuid,nodev,noexec,relatime,memory 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/freezer cgroup ro,nosuid,nodev,noexec,relatime,freezer 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/blkio cgroup ro,nosuid,nodev,noexec,relatime,blkio 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/cpuset cgroup ro,nosuid,nodev,noexec,relatime,cpuset 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/perf_event cgroup ro,nosuid,nodev,noexec,relatime,perf_event 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/devices cgroup ro,nosuid,nodev,noexec,relatime,devices 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/systemd cgroup ro,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/hugetlb cgroup ro,nosuid,nodev,noexec,relatime,hugetlb 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/net_cls,net_prio cgroup ro,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/cpu,cpuacct cgroup ro,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/pids cgroup ro,nosuid,nodev,noexec,relatime,pids 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/memory cgroup ro,nosuid,nodev,noexec,relatime,memory 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/freezer cgroup ro,nosuid,nodev,noexec,relatime,freezer 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/blkio cgroup ro,nosuid,nodev,noexec,relatime,blkio 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/cpuset cgroup ro,nosuid,nodev,noexec,relatime,cpuset 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/perf_event cgroup ro,nosuid,nodev,noexec,relatime,perf_event 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/rootfs/var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/devices cgroup ro,nosuid,nodev,noexec,relatime,devices 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
	cgroup /var/lib/docker/aufs/mnt/78d3ceae2050a76d71673a00daaa68b976786079563f2d6197c7bd752126154f/sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0


Docker version: [Supported and recommended]
	Docker version is 1.12.1. Versions >= 1.0 are supported. 1.2+ are recommended.


Docker driver setup: [Supported and recommended]
	Docker exec driver is . Storage driver is aufs.


Block device setup: [Supported and recommended]
	At least one device supports 'cfq' I/O scheduler. Some disk stats can be reported.
	 Disk "sda" Scheduler type "cfq".


Inotify watches: 
	

Managed containers: 
	/system.slice/systemd-timesyncd.service
	/system.slice/ssh.service
	/system.slice/dev-disk-by\x2dpath-pci\x2d0000:00:1f.2\x2data\x2d1\x2dpart5.swap
	/system.slice/ModemManager.service
	/system.slice/apport.service
	/system.slice/systemd-logind.service
	/system.slice/networking.service
	/system.slice/var-lib-docker-containers-a98c6e4edc74737b42ea030a8e01c242ad060926dd4888224ee8988680a43f02-shm.mount
		Namespace: docker
		Aliases:
			cadvisor
			a98c6e4edc74737b42ea030a8e01c242ad060926dd4888224ee8988680a43f02
	/system.slice/accounts-daemon.service
	/system.slice/systemd-journal-flush.service
	/system.slice/irqbalance.service
	/system.slice/rsyslog.service
	/system.slice/ondemand.service
	/system.slice/thermald.service
	/system.slice/NetworkManager.service
	/system.slice/keyboard-setup.service
	/system.slice/dev-disk-by\x2did-wwn\x2d0x5000c5005daac616\x2dpart5.swap
	/system.slice/alsa-restore.service
	/system.slice/dev-disk-by\x2duuid-d653327d\x2d500d\x2d48e8\x2da104\x2d067a77778211.swap
	/system.slice/systemd-journald.service
	/system.slice/resolvconf.service
	/system.slice/acpid.service
	/system.slice/lightdm.service
	/system.slice/dev-disk-by\x2did-ata\x2dST250DM000\x2d1BD141_W2AMDZXN\x2dpart5.swap
	/system.slice/systemd-tmpfiles-setup-dev.service
	/init.scope
	/system.slice/speech-dispatcher.service
	/docker
	/system.slice/rtkit-daemon.service
	/system.slice/upower.service
	/system.slice/systemd-user-sessions.service
	/system.slice/udisks2.service
	/system.slice/apparmor.service
	/system.slice/snapd.service
	/system.slice/systemd-tmpfiles-setup.service
	/
	/system.slice/setvtrgb.service
	/system.slice/systemd-udev-trigger.service
	/system.slice/systemd-sysctl.service
	/system.slice/systemd-random-seed.service
	/system.slice/systemd-udevd.service
	/system.slice/dev-sda5.swap
	/system.slice/systemd-remount-fs.service
	/system.slice/rc-local.service
	/system.slice/kmod-static-nodes.service
	/system.slice/docker.service
	/system.slice/console-setup.service
	/system.slice/cgroupfs-mount.service
	/system.slice
	/system.slice/ufw.service
	/system.slice/polkitd.service
	/system.slice/cron.service
	/user.slice
	/system.slice/systemd-update-utmp.service
	/system.slice/system-getty.slice
	/docker/a98c6e4edc74737b42ea030a8e01c242ad060926dd4888224ee8988680a43f02
		Namespace: docker
		Aliases:
			cadvisor
			a98c6e4edc74737b42ea030a8e01c242ad060926dd4888224ee8988680a43f02
	/system.slice/dbus.service
	/system.slice/whoopsie.service
	/docker/5ae6127048c41324f1b9b06573a00d1d2dcd030b572d9d4e997f6494a1404706
		Namespace: docker
		Aliases:
			kickass_goldstine
			5ae6127048c41324f1b9b06573a00d1d2dcd030b572d9d4e997f6494a1404706
	/system.slice/colord.service
	/system.slice/grub-common.service
	/system.slice/systemd-modules-load.service
```

**Comment by barnettZQG** [comment] 2016-08-31 02:31
@skebo
you could use docker api about cgroup.it could get blkio stats

**Comment by renatosis** [comment] 2017-01-18 16:10
Hi @skebo , did u solve this issue? how?

Thanks

**Comment by skebo** [comment] 2017-01-19 18:15
no @renatosis, i did not solve this problem and didn't see any progress, so we've moved away from cadvisor.

**Comment by k-s-dean** [comment] 2017-01-24 15:18
@skebo Out of interest what did you move to ? I am surprised that none of the cadvisor maintainers or developers are willing to let us know why 0 is being returned.

**Comment by skebo** [comment] 2017-01-24 17:29
@k-s-dean we moved to Datadog.  I'd really prefer a non-commercial solution, so I was also very disappointed by the flaw.  However, the lack of response on this issue was really what sealed the deal.  There was no indication that this problem would ever be addressed.

**Comment by dashpole** [comment] 2017-03-17 00:02
duplicate of #1403

**Closed by dashpole** 2017-03-17 00:02 UTC
Labels: closed/duplicate
