### ISSUE TITLE
Make Docker APIs in manager generic

### ISSUE THREAD

**Issue by sjpotter** [google/cadvisor#1276] opened 2016-05-08 08:27 UTC
I see a handful of APIs that are docker specific

AllDockerContainers(query *info.ContainerInfoRequest) (map[string]info.ContainerInfo, error)
DockerContainer(dockerName string, query *info.ContainerInfoRequest) (info.ContainerInfo, error)
DockerInfo() (info.DockerStatus, error)
DockerImages() ([]info.DockerImage, error)

I'm honestly unsure how t ohandle DockerInfo(), but the rest are probably along the lines of

AllNamespacedContainers(containerNamespace string, query *info.ContainerInfoRequest)

NamespacedContainer(containerName string, containerNamespace string, query *info.ContainerInfoRequest)

RuntimeImages(containerNamespace string)

**Comment by timstclair** [comment] 2016-05-09 21:51
Duplicate of https://github.com/google/cadvisor/issues/1177

**Closed by timstclair** 2016-05-09 21:51 UTC
