### ISSUE TITLE
cadvisor start failing intermittently with panic message

### ISSUE THREAD

**Issue by ashokkannan** [google/cadvisor#1626] opened 2017-03-20 15:26 UTC
I'm trying to run cadvisor as a service in oracle linux  box (not running as docker). Sometimes its coming up fine ,but most of the time I'm seeing the below panic message. I don't see any other error message in any of the system logs. So I don't have a clue about this issue. Any details or pointers will be of great help.

Command:  cadvisor -port 9056
Error:
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x63 pc=0x7f4820d4e67d]

runtime stack:
runtime.throw(0xfdc760, 0x2a)
	/home/stclair/.gvm/gos/go1.6.3/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/home/stclair/.gvm/gos/go1.6.3/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 106 [syscall, locked to thread]:
runtime.cgocall(0xabb6c0, 0xc8202dfbd8, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/runtime/cgocall.go:123 +0x11b fp=0xc8202dfb78 sp=0xc8202dfb48
net._C2func_getaddrinfo(0x7f48040008c0, 0x0, 0xc820333a70, 0xc82007e058, 0x0, 0x0, 0x0)
	??:0 +0x55 fp=0xc8202dfbd8 sp=0xc8202dfb78
net.cgoLookupIPCNAME(0xec20a0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/net/cgo_unix.go:111 +0x448 fp=0xc8202dfd50 sp=0xc8202dfbd8
net.cgoLookupIP(0xec20a0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/net/cgo_unix.go:163 +0x56 fp=0xc8202dfda8 sp=0xc8202dfd50
net.lookupIP(0xec20a0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/net/lookup_unix.go:67 +0x94 fp=0xc8202dfe18 sp=0xc8202dfda8
net.glob.func16(0x1072270, 0xec20a0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/net/hook.go:10 +0x4d fp=0xc8202dfe58 sp=0xc8202dfe18
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/net/lookup.go:106 +0x71 fp=0xc8202dfed8 sp=0xc8202dfe58
internal/singleflight.(*Group).doCall(0x16459c0, 0xc820355180, 0xec20a0, 0x9, 0xc82024a180)
	/home/stclair/.gvm/gos/go1.6.3/src/internal/singleflight/singleflight.go:93 +0x2c fp=0xc8202dff88 sp=0xc8202dfed8
runtime.goexit()
	/home/stclair/.gvm/gos/go1.6.3/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8202dff90 sp=0xc8202dff88
created by internal/singleflight.(*Group).DoChan
	/home/stclair/.gvm/gos/go1.6.3/src/internal/singleflight/singleflight.go:86 +0x3ee

goroutine 1 [select]:
net.lookupIPDeadline(0xec20a0, 0x9, 0xed061e431, 0x22a21fab, 0x1646980, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/net/lookup.go:109 +0x6a6
net.internetAddrList(0xea77a8, 0x3, 0xec20a0, 0xf, 0xed061e431, 0x22a21fab, 0x1646980, 0x0, 0x0, 0x0, ...)
	/home/stclair/.gvm/gos/go1.6.3/src/net/ipsock.go:252 +0x6ee
net.resolveAddrList(0xea3050, 0x4, 0xea77a8, 0x3, 0xec20a0, 0xf, 0xed061e431, 0x22a21fab, 0x1646980, 0x0, ...)
	/home/stclair/.gvm/gos/go1.6.3/src/net/dial.go:158 +0x466
net.(*Dialer).Dial(0xc8202b75b0, 0xea77a8, 0x3, 0xec20a0, 0xf, 0x0, 0x0, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/net/dial.go:216 +0x124
net.DialTimeout(0xea77a8, 0x3, 0xec20a0, 0xf, 0x77359400, 0x0, 0x0, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/net/dial.go:200 +0xa3
github.com/google/cadvisor/container/rkt.Client.func1()
	/home/stclair/go/src/github.com/google/cadvisor/container/rkt/client.go:44 +0x59
sync.(*Once).Do(0x166c260, 0x10713a8)
	/home/stclair/.gvm/gos/go1.6.3/src/sync/once.go:44 +0xe4
github.com/google/cadvisor/container/rkt.Client(0x0, 0x0, 0x0, 0x0)
	/home/stclair/go/src/github.com/google/cadvisor/container/rkt/client.go:79 +0x47
github.com/google/cadvisor/container/rkt.RktPath(0x0, 0x0, 0x0, 0x0)
	/home/stclair/go/src/github.com/google/cadvisor/container/rkt/client.go:85 +0x48
github.com/google/cadvisor/manager.New(0xc82038bf40, 0x7f4822777208, 0x166c1b8, 0xdf8475800, 0x7f482276b501, 0xc8203a3c50, 0xc8203a3e30, 0x0, 0x0, 0x0, ...)
	/home/stclair/go/src/github.com/google/cadvisor/manager/manager.go:146 +0x341
main.main()
	/home/stclair/go/src/github.com/google/cadvisor/cadvisor.go:127 +0x654

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/stclair/.gvm/gos/go1.6.3/src/runtime/asm_amd64.s:1998 +0x1

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/home/stclair/.gvm/gos/go1.6.3/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/home/stclair/.gvm/gos/go1.6.3/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [chan receive]:
github.com/google/cadvisor/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1646ce0)
	/home/stclair/go/src/github.com/google/cadvisor/vendor/github.com/golang/glog/glog.go:882 +0x67
created by github.com/google/cadvisor/vendor/github.com/golang/glog.init.1
	/home/stclair/go/src/github.com/google/cadvisor/vendor/github.com/golang/glog/glog.go:410 +0x297

goroutine 114 [IO wait]:
net.runtime_pollWait(0x7f4822778348, 0x72, 0xc8202fe000)
	/home/stclair/.gvm/gos/go1.6.3/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203dca70, 0x72, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203dca70, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203dca10, 0xc8202fe000, 0x1000, 0x1000, 0x0, 0x7f4822767050, 0xc820010190)
	/home/stclair/.gvm/gos/go1.6.3/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820356238, 0xc8202fe000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f4822778408, 0xc820356238, 0xc8200c26e8, 0xc8202fe000, 0x1000, 0x1000, 0x409fb3, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/net/http/transport.go:1690 +0x67
net/http.(*noteEOFReader).Read(0xc8203c9840, 0xc8202fe000, 0x1000, 0x1000, 0xc82008dd1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8200c0960)
	/home/stclair/.gvm/gos/go1.6.3/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8200c0960, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/stclair/.gvm/gos/go1.6.3/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200c2680)
	/home/stclair/.gvm/gos/go1.6.3/src/net/http/transport.go:1076 +0x177
created by net/http.(*Transport).dialConn
	/home/stclair/.gvm/gos/go1.6.3/src/net/http/transport.go:860 +0x10a6

goroutine 115 [select]:
net/http.(*persistConn).writeLoop(0xc8200c2680)
	/home/stclair/.gvm/gos/go1.6.3/src/net/http/transport.go:1280 +0x472
created by net/http.(*Transport).dialConn
	/home/stclair/.gvm/gos/go1.6.3/src/net/http/transport.go:861 +0x10cb

Host Details:
Oracle Linux 7.1
4.1.12-61.1.10.el7uek.x86_64

Thanks

**Comment by dashpole** [comment] 2017-03-20 16:21
only interesting thing I see is: `cadvisor/container/rkt/client.go:44`, which is a call to `net.DialTimeout("tcp", "localhost:15441", 2*time.Second).
I am not sure why this would panic...
https://github.com/golang/go/issues/6232 suggests this could be related to dns failures, which would make sense, since the top of that trace has `lookupIPDeadline`

**Comment by timstclair** [comment] 2017-03-20 17:38
Duplicate of https://github.com/google/cadvisor/issues/1481

**Closed by timstclair** 2017-03-20 17:38 UTC
Labels: kind/support
