### ISSUE TITLE
Failed to create summary reader

### ISSUE THREAD

**Issue by jeinwag** [google/cadvisor#1168] opened 2016-03-17 10:29 UTC
I noticed that sometimes, after they've restarted a couple of times, containers are no longer being tracked by cadvisor.

This is the error message from cadvisor log:

```
W0317 03:48:37.894884       1 container.go:341] Failed to create summary reader for "/docker/321dc03291bd47757c2fe6415d084b21a516c7d73a865c0                                                                                                 982d9333ca36aee70": none of the resources are being tracked.
W0317 03:48:37.895065       1 manager.go:1022] Failed to process watch event: failed to read libcontainer config: open /var/lib/docker/execd                                                                                                 river/native/321dc03291bd47757c2fe6415d084b21a516c7d73a865c0982d9333ca36aee70/container.json: no such file or directory
W0317 04:00:01.151372       1 container.go:341] Failed to create summary reader for "/docker/321dc03291bd47757c2fe6415d084b21a516c7d73a865c0                                                                                                 982d9333ca36aee70": none of the resources are being tracked.
W0317 04:00:01.151412       1 manager.go:1022] Failed to process watch event: failed to read libcontainer config: open /var/lib/docker/execd                                                                                                 river/native/321dc03291bd47757c2fe6415d084b21a516c7d73a865c0982d9333ca36aee70/container.json: no such file or directory
```

The application running in the container crashed at 3:48 and 4:00.

Cadvisor still correctly lists the container as, but when trying to get some details, I get the following error message:

```
failed to get container "/docker/321dc03291bd47757c2fe6415d084b21a516c7d73a865c0982d9333ca36aee70" with error: unable to find data for container /docker/321dc03291bd47757c2fe6415d084b21a516c7d73a865c0982d9333ca36aee70 
```

**Comment by yujuhong** [comment] 2016-04-13 18:42
What version of docker do you use and what are the flags?

**Comment by wjimenez5271** [comment] 2016-04-14 18:06
I'm observing something similar.

Docker version 1.9.1, build a34a1d5/1.9.1 on Amazon Linux AMI release 2016.03

```
docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --volume=/cgroup:/cgroup:ro \
  --publish=9070:8080 \
  --detach=true \
  --privileged=true \
  --name=cadvisor \
  --restart=unless-stopped \
  google/cadvisor:latest
```

**Comment by jeinwag** [comment] 2016-04-21 09:51
We're using docker 1.10.2
```
sudo docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=9090:8080 \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest
```

**Comment by yujuhong** [comment] 2016-04-21 19:56
@jeinwag By "restarting", do you mean that you called `docker restart`, or uses docker's restart policy?

Did those files that cadvisor tried to access existed at the time you check?

**Comment by jeinwag** [comment] 2016-04-22 06:05
@yujuhong The container did restart because the application running inside the container did crash (the container was created with restart-policy 'on failure'). Unfortunately, the issue causing the application crash has been fixed since, so I can't reproduce the issue any longer.

**Comment by binman-docker** [comment] 2016-04-25 18:28
We're seeing the same thing, not necessarily linked to restarts, though it does seem to always be the same containers. Running cadvisor 0.22 on docker engine 1.9.1.

```user@host:/var/lib/docker# docker logs cadvisor 2>&1 | grep 8d97417dfabd
W0424 05:15:16.991521       1 container.go:341] Failed to create summary reader for "/docker/8d97417dfabd2c58edc9a67137260a16d022c44f8aad4a7abbf224f2a087123a": none of the resources are being tracked.
W0424 05:15:16.992561       1 manager.go:1022] Failed to process watch event: failed to read libcontainer config: open /var/lib/docker/execdriver/native/8d97417dfabd2c58edc9a67137260a16d022c44f8aad4a7abbf224f2a087123a/container.json: no such file or directory
W0424 06:22:32.339289       1 container.go:341] Failed to create summary reader for "/docker/8d97417dfabd2c58edc9a67137260a16d022c44f8aad4a7abbf224f2a087123a": none of the resources are being tracked.
W0424 06:22:32.339352       1 manager.go:1022] Failed to process watch event: failed to read libcontainer config: open /var/lib/docker/execdriver/native/8d97417dfabd2c58edc9a67137260a16d022c44f8aad4a7abbf224f2a087123a/container.json: no such file or directory
W0424 06:50:25.392315       1 container.go:341] Failed to create summary reader for "/docker/8d97417dfabd2c58edc9a67137260a16d022c44f8aad4a7abbf224f2a087123a": none of the resources are being tracked.
W0424 06:50:25.392378       1 manager.go:1022] Failed to process watch event: failed to read libcontainer config: open /var/lib/docker/execdriver/native/8d97417dfabd2c58edc9a67137260a16d022c44f8aad4a7abbf224f2a087123a/container.json: no such file or directory
```

The directory "/var/lib/docker/execdriver" does not exist at all (/var/lib/docker does, of course).

Accessing the container in the webui gets this:
```failed to get container "/docker/8d97417dfabd2c58edc9a67137260a16d022c44f8aad4a7abbf224f2a087123a" with error: unable to find data for container /docker/8d97417dfabd2c58edc9a67137260a16d022c44f8aad4a7abbf224f2a087123a
```

Restarting the cadvisor container fixes the issue. I can include the /validate if that would help.

**Comment by yujuhong** [comment] 2016-05-02 23:53
I am not familiar with the cadvisor codebase, but this is my guess.

For some reason (race condition or transient error?), sometimes cadvisor cannot read the docker configuration file (`state.json` or `container.json` depending on the versions of docker). cadvisor reports an error but does not retry at all. I can reproduce the error messages periodically by forcing the container to restart every 10s: `sudo docker run --restart=always -d busybox /bin/sh -c "sleep 10"`

Note that in HEAD (cadvisor 0.23), cadvisor no longer reads the config files from docker, so this problem should be resolved after upgrade. However, It'd also be a good idea to retry getting the spec of the container.

/cc @timstclair

**Comment by dashpole** [comment] 2017-03-16 21:27
Closing, since we no longer read docker config files.

**Closed by dashpole** 2017-03-16 21:27 UTC
Labels: kind/support, runtime/docker
