### ISSUE TITLE
cadvisor api response return unable to find data error if  docker initializes container

### ISSUE THREAD

**Issue by Betula-L** [google/cadvisor#2003] opened 2018-07-18 11:51 UTC
I have a job to `Get localhost/api/v1.3/docker` per 400ms.

If `docker run containerX`, then `Get /api/v1.3/docker` failed.

And response content is as follow:

`
 Response Body: failed to get all Docker containers with error: unable to find data for container 6606c5ff69b587198af8eaea5554b494e7982277c24bfb701554fd5756577
Response Code: 500 
`

It seems that, when docker started to initialize containers and didn't finished yet, some essential information in cgroup can not require by cadvisor, then /api/v1.3/docker failed.

Cadvisor run as follow:

`
docker run   --volume=/:/rootfs:ro   --volume=/var/run:/var/run:rw   --volume=/sys:/sys:ro   --volume=/var/lib/docker/:/var/lib/docker:ro   --publish=8080:8080   --detach=true   --name=cadvisor   google/cadvisor:latest
`

**Comment by dashpole** [comment] 2018-07-18 16:57
This sounds like a duplicate of https://github.com/google/cadvisor/issues/1970.  Can you try with the canary version of cAdvisor (google/cadvisor:canary)?

**Comment by Betula-L** [comment] 2018-07-19 02:13
It's fixed in `google/cadvisor:canary`

**Closed** 2018-12-26 07:36 UTC
